### ISSUE TITLE
PR requirements & template

### ISSUE THREAD

**Issue by EigenSolver** [EvoEvolver/EvoNote#15]
We need a a brief Wikipedia for the requirements of PR(pull request), like coding norms, descriptions of commits, etc. So we can better collaborate.

**Comment by doomspec** [comment]
I think descriptions of commits are needed and I will try to set up Pylint later as coding norms. I am not familiar with PR. Maybe you can make some rule there?

**Comment by EigenSolver** [comment]
Hi I think GPT has given a quite good suggestion on this issue together with a PR template. 
I will implement the template if you like it. 
But before that, we need to determine a standard for code norm. Pylint is good to me. Maybe you can consult other team mates before make decision.

## Answer from GPT4:
Certainly! The concept of a pull request (PR) template is centered around improving code quality, ensuring clarity and understanding among contributors, and easing the process of code review. Instituting a standard PR template can greatly benefit the development process by setting clear expectations and reducing the likelihood of incomplete or suboptimal contributions.

### Why Use a PR Template?

1. **Consistency**: A standard format for all pull requests makes it easier to understand and review.
2. **Efficiency**: Reduces back-and-forth by requesting all necessary information upfront.
3. **Documentation**: Provides a consistent history of changes which can be valuable for future reference.
4. **Code Quality**: Ensures contributors have checked, tested, and verified their changes.
5. **Education**: Reminds new contributors of the necessary steps and checks.

### Standard Sections for a PR Template:

1. **Title/Description**: A clear, concise summary of what the PR achieves.
   
2. **Issue/Task Link**: Reference to any associated tickets, issues, or tasks that this PR addresses. This provides context for why the change is necessary.
   
3. **Type of Change**: Whether it's a bugfix, feature, documentation update, etc.
   
4. **Testing**: Explanation of what testing was done, how to reproduce any tests, or why testing wasn't needed.
   
5. **Checklist**: A list of tasks that the author confirms they've completed. This can include:
   - [ ] Code follows the project's style guide.
   - [ ] Code has been commented, particularly in hard-to-understand areas.
   - [ ] Changes are added to the documentation.
   - [ ] Tests have been added to verify the change.
   - [ ] All new and existing tests passed.
   
6. **Screenshots**: Especially for UI changes, a visual representation can be invaluable.
   
7. **Additional Context**: Any other information that might help reviewers understand the PR.

### Sample PR Template:

```
### Description

[Description of the pull request. Should be a clear and concise description of what the PR achieves.]

Fixes #[issue-number]

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

### Checklist:

- [ ] I have followed the project's style guidelines.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings or errors.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] All new and existing tests passed.

### Screenshots (if appropriate)

### Additional Context

```

### Final Thoughts:

While the above is a general template, it's important to adapt it based on the specific needs of your project. Some projects might need additional sections or have unique guidelines. It's also essential to periodically review and update the template based on the feedback from contributors and changes in the development process.

Remember that a PR template is a tool. It's meant to be helpful, not restrictive. The goal is to facilitate clearer communication and maintain the quality of the codebase.
