### ISSUE TITLE
Mythological system test set for understanding

### ISSUE THREAD

**Issue by doomspec** [EvoEvolver/EvoNote#9]
We want to test a model of understanding by making it understand Mythology. This is because 

- Myth is a major way to understand things in the whole of human history.
- Myth is simpler to understand than science
- Myth is not fact and can be altered to test the one-shot understanding ability

Ideas:

- Replace names in Norse Mythology with Chinese names and try to make the model understand it.
- SCP style stories

Requirement:

- Longer than the prompt window
- Stories should be untrue and weird.

The test story can be put in the test folder

**Comment by doomspec** [comment]
I just uploaded an example: evonote/testing/sample_notebook/dingzhen_world.py

We definitely need to add more stories to it.

**Comment by EigenSolver** [comment]
I plan to use the Wikipedia of the fictional nation, Listenbourg (https://en.wikipedia.org/wiki/Listenbourg) to test the understanding functionality, which would requires the implementation of HTML parser first.
